# 1. Numpy exercises

a. Create a null vector of size 10 but the fifth value which is 1


In [6]:
import numpy as np
vec = np.zeros(10)
vec[4] = 1
print(vec)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


b. Create a vector with values ranging from 10 to 49

In [18]:
vec2 = np.linspace(10, 49, num=20)


array([10.        , 12.05263158, 14.10526316, 16.15789474, 18.21052632,
       20.26315789, 22.31578947, 24.36842105, 26.42105263, 28.47368421,
       30.52631579, 32.57894737, 34.63157895, 36.68421053, 38.73684211,
       40.78947368, 42.84210526, 44.89473684, 46.94736842, 49.        ])

c. Reverse a vector (first element becomes last)


In [22]:
vec3 = np.flip(vec2)
vec3

array([49.        , 46.94736842, 44.89473684, 42.84210526, 40.78947368,
       38.73684211, 36.68421053, 34.63157895, 32.57894737, 30.52631579,
       28.47368421, 26.42105263, 24.36842105, 22.31578947, 20.26315789,
       18.21052632, 16.15789474, 14.10526316, 12.05263158, 10.        ])

d. Create a 3x3 matrix with values ranging from 0 to 8

In [80]:
vec3 = np.arange(9).reshape(3,3)
vec3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

e. Find indices of non-zero elements from [1,2,0,0,4,0]


In [81]:
vec4 = np.array([1,2,0,0,4,0])
np.nonzero(vec4)


(array([0, 1, 4], dtype=int64),)

f. Create a random vector of size 30 and find the mean value


In [77]:
vec5 = np.random.rand(30)
# vec5.shape
vec5


array([0.41560239, 0.86314632, 0.07792052, 0.36941952, 0.60235982,
       0.26716577, 0.76153426, 0.51195763, 0.91942297, 0.65842174,
       0.72490738, 0.34421465, 0.31585286, 0.33386456, 0.76855091,
       0.63822755, 0.62434248, 0.6313119 , 0.79465716, 0.33641236,
       0.80465846, 0.91688726, 0.25178466, 0.31576792, 0.8535181 ,
       0.96475947, 0.77545198, 0.91734377, 0.35753732, 0.18414919])

In [78]:
 np.mean(vec5)

0.5767050289484827

g. Create a 2d array with 1 on the border and 0 inside


In [93]:
mat1 = np.ones(9, dtype=int).reshape(3,3)
mat1[1:-1,1:-1]=0
mat1


array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

h. Create a 8x8 matrix and fill it with a checkerboard pattern

In [231]:
#loop functino to ficx diagonals
def change_digonal(matrix, s_nr, numb=1):
    np.fill_diagonal(matrix[:-s_nr,s_nr:],numb)
    np.fill_diagonal(matrix[s_nr:,:-s_nr],numb)

#task
n = 8
cb_mat =np.eye(n)
for i in range(len(cb_mat.diagonal())):
    if i % 2 == 0:
        change_digonal(cb_mat, i, 1)
cb_mat
   
    

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [284]:
#Other method h.
n=8
cb_mat2 = np.zeros((n,n), dtype=int)
#slicing: x1-first part startpos in matrix, x2- endposition, steps ibetween x1x2
cb_mat3[1::2,::2] = 1
cb_mat3[::2,1::2] = 1

cb_mat3

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

i. Create a checkerboard 8x8 matrix using the tile function

In [285]:
n=8
pat=[1 ,0]
seq =np.tile([pat,np.flip(pat)],(n//2, n//2))
seq


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

j. Given a 1D array, negate all elements which are between 3 and 8, in place


In [302]:
Z = np.arange(11)
Z[3:9] = np.negative(Z[3:9])
Z

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

k. Create a random vector of size 10 and sort it


In [309]:
Z = np.random.random(10)
Z.sort()
print(Z)


[0.09579904 0.16767417 0.18877258 0.19226298 0.5268532  0.55231679
 0.81161922 0.81526872 0.92591128 0.95454868]


l. Consider two random array A anb B, check if they are equal

In [338]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
eq = np.array_equal(A,B)
print(eq)
print(A)
print(B)


False
[1 1 0 0 0]
[0 1 1 1 1]


m. How to convert an integer (32 bits) array into a float (32 bits) in place?

In [350]:
Z = np.arange(10, dtype=np.int32)

print(Z.dtype)
Z = Z.view(dtype=np.float32)
print(Z.dtype)

int32
float32


n. How to get the diagonal of a dot product?

In [356]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.dot(A,B).diagonal()
print(A)
print(B)
print(C)
print(D)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]


2. Already done day2 using numpy

3. Examples on classes and inheritance in Python

a. Create a "Person" class which takes firstname and lastname as arguments to the constructor (___init___) and define a method that returns the full name of the person as a combined string.

b. Create a "Student" class which inherits from the "Person" class, takes the subject area as an additional argument to the constructor and define a method that prints the full name and the subject area of the student.

In [364]:
Solutuions in addidtional files, not in Jupyter                      
    
    

In [ ]:
In [1]: from classroom import Student
In [2]: me = Student('Benedikt', 'Daurer', 'physics') 
In [3]: me.printNameSubject() 
Benedikt Daurer, physics